version: "3.7"
services:
  almot:
    build:
      args:
        user: rahanpas
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: lmot
    container_name: lmot-almot
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - lmot

  nginx:
    image: nginx:alpine
    container_name: lmot-nginx
    restart: unless-stopped
    ports:
      - 7696:8213
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lmot

networks:
  lmot:
    driver: bridge
